---
title: "Table 2 (and additional tables)"
author: "Mathew Kiang"
date: "11/15/2020"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setting up
```{r error=FALSE, message=FALSE, warning=FALSE, results='hide'}
## Imports ----
library(tidyverse)
library(here)
library(fs)
library(knitr)
source(here("code", "utils.R"))

## Constants ----
PROB_INF <- config::get()$primary_prob_inf / 1000000
```

```{r error=FALSE, message=FALSE, warning=FALSE}
## End of travel period infection stats
inf_df <- readRDS(here("data", "summarized_results.RDS")) %>%
    filter(
        time_step == 84, 
        if_threshold == 0,
        prob_inf == PROB_INF,
        risk_multiplier == 2,
        testing_type != "perfect_testing",
        rapid_test_multiplier == .9 |
            is.na(rapid_test_multiplier),
        sens_type != "median" | is.na(sens_type),
        prop_subclin == .3,
        symptom_adherence %in% c(0, .8),
        quarantine_adherence %in% c(0, .8),
        testing_type %in% c(
            "no_testing",
            "pcr_three_days_before",
            "pcr_three_days_before_5_day_quarantine_pcr",
            "rapid_test_same_day",
            "rapid_same_day_5_day_quarantine_pcr",
            "pcr_five_days_after"
        )
    ) %>%
    shift_time_steps() %>%
    categorize_metric() %>%
    filter(metric %in% c("cume_n_infection_daily",
                         "rel_cume_n_infection_daily"))

## Subset to the main analyses ----
inf_df <- bind_rows(
    ## No testing no symptom screening
    inf_df %>%
        filter(testing_type == "no_testing" &
                   symptom_adherence == 0),
    ## No quarantine 80% symptom screening adherence
    inf_df %>%
        filter(
            testing_type %in% c(
                "pcr_three_days_before",
                "rapid_test_same_day",
                "pcr_five_days_after"
            ) & 
                symptom_adherence == .8
        ),
    ## With 80% quarantine and 80% symptom screening adherence
    inf_df %>% 
        filter(
            testing_type %in% c(
                "pcr_three_days_before_5_day_quarantine_pcr",
                "rapid_same_day_5_day_quarantine_pcr"
            ) & 
                symptom_adherence == .8 & 
                quarantine_adherence == .8
        )
) 

## Testing statistics 
test_df <- readRDS(here("data", "summarized_testing_results.RDS"))

test_df <- test_df %>%
    filter(
        risk_multiplier == 2,
        testing_type %in% c(
            "no_testing",
            "pcr_three_days_before",
            "pcr_three_days_before_5_day_quarantine_pcr",
            "rapid_test_same_day",
            "rapid_same_day_5_day_quarantine_pcr",
            "pcr_five_days_after"
        ), 
        metric %in% c("ratio_false_true"),
        rapid_test_multiplier == .9 | is.na(rapid_test_multiplier),
        prob_inf == PROB_INF,
        prop_subclin == .3, 
        sens_type != "median" | is.na(sens_type),
        if_threshold == 0,
        symptom_adherence %in% c(0, .8)
    ) %>%
    categorize_metric()

test_df <- bind_rows(
    ## No testing no symptom screening
    test_df %>%
        filter(testing_type == "no_testing" &
                   symptom_adherence == 0),
    test_df %>%
        filter(testing_type != "no_testing" &
                   symptom_adherence == .8)
) 

## Day of flight statistics
dof_df <- readRDS(here("data", "summarized_results.RDS")) %>%
    filter(
        time_step == 70, 
        if_threshold == 0,
        prob_inf == PROB_INF,
        risk_multiplier == 2,
        testing_type != "perfect_testing",
        rapid_test_multiplier == .9 |
            is.na(rapid_test_multiplier),
        sens_type != "median" | is.na(sens_type),
        prop_subclin == .3,
        symptom_adherence %in% c(0, .8),
        quarantine_adherence %in% c(0, .8),
        testing_type %in% c(
            "no_testing",
            "pcr_three_days_before",
            "pcr_three_days_before_5_day_quarantine_pcr",
            "rapid_test_same_day",
            "rapid_same_day_5_day_quarantine_pcr",
            "pcr_five_days_after"
        )
    ) %>%
    shift_time_steps() %>%
    categorize_metric() %>%
    filter(metric %in% c("n_active_infection", "rel_n_active_infection"))

dof_df <- bind_rows(
    ## No testing no symptom screening
    dof_df %>%
        filter(testing_type == "no_testing" &
                   symptom_adherence == 0),
    ## No quarantine 80% symptom screening adherence
    dof_df %>%
        filter(
            testing_type %in% c(
                "pcr_three_days_before",
                "rapid_test_same_day",
                "pcr_five_days_after"
            ) & 
                symptom_adherence == .8
        ),
    ## With 80% quarantine and 80% symptom screening adherence
    dof_df %>% 
        filter(
            testing_type %in% c(
                "pcr_three_days_before_5_day_quarantine_pcr",
                "rapid_same_day_5_day_quarantine_pcr"
            ) & 
                symptom_adherence == .8 & 
                quarantine_adherence == .8
        )
) 

## All main outcomes
all_df <- bind_rows(
    dof_df,
    inf_df,
    test_df
)

print_df <- all_df %>%
    select(testing_cat, metric, mean, p025, p975) %>%
    arrange(testing_cat, metric) %>%
    transmute(testing_cat,
              metric,
              print = case_when(
                  metric %in% c("cume_n_infection_daily", "n_active_infection") ~
                      sprintf("%i (%i, %i)",
                              round(mean),
                              round(p025),
                              round(p975)),
                  TRUE ~ sprintf(
                      "%0.2f (%0.2f, %0.2f)",
                      round(mean, 2),
                      round(p025, 2),
                      round(p975, 2)
                  )
              )) %>%
    pivot_wider(id_cols = testing_cat,
                names_from = metric,
                values_from = print) %>%
    select(
        testing_cat,
        cume_n_infection_daily,
        rel_cume_n_infection_daily,
        n_active_infection,
        rel_n_active_infection,
        ratio_false_true
    )
```

##  Table 1
```{r}
print_df <- all_df %>%
    select(testing_cat, metric, mean, p025, p975) %>%
    arrange(testing_cat, metric) %>%
    transmute(testing_cat,
              metric,
              print = case_when(
                  metric %in% c("cume_n_infection_daily", "n_active_infection") ~
                      sprintf("%i (%i, %i)",
                              round(mean),
                              round(p025),
                              round(p975)),
                  TRUE ~ sprintf(
                      "%0.2f (%0.2f, %0.2f)",
                      round(mean, 2),
                      round(p025, 2),
                      round(p975, 2)
                  )
              )) %>%
    pivot_wider(id_cols = testing_cat,
                names_from = metric,
                values_from = print) %>%
    select(
        testing_cat,
        cume_n_infection_daily,
        rel_cume_n_infection_daily,
        n_active_infection,
        rel_n_active_infection,
        ratio_false_true
    ) 

print_df %>%
  kable()
```

## Table S2 Post-travel infectious days only
```{r error=FALSE, message=FALSE, warning=FALSE}
## End of travel period infection stats
inf_df <- readRDS(here("data", "summarized_results_postflight.RDS")) %>%
    filter(
        time_step == 84, 
        if_threshold == 0,
        prob_inf == PROB_INF,
        risk_multiplier == 2,
        testing_type != "perfect_testing",
        rapid_test_multiplier == .9 |
            is.na(rapid_test_multiplier),
        sens_type != "median" | is.na(sens_type),
        prop_subclin == .3,
        symptom_adherence %in% c(0, .8),
        quarantine_adherence %in% c(0, .8),
        testing_type %in% c(
            "no_testing",
            "pcr_three_days_before",
            "pcr_three_days_before_5_day_quarantine_pcr",
            "rapid_test_same_day",
            "rapid_same_day_5_day_quarantine_pcr",
            "pcr_five_days_after"
        )
    ) %>%
    shift_time_steps() %>%
    categorize_metric() %>%
    filter(metric %in% c("cume_n_infection_daily",
                         "rel_cume_n_infection_daily"))

## Subset to the main analyses ----
inf_df <- bind_rows(
    ## No testing no symptom screening
    inf_df %>%
        filter(testing_type == "no_testing" &
                   symptom_adherence == 0),
    ## No quarantine 80% symptom screening adherence
    inf_df %>%
        filter(
            testing_type %in% c(
                "pcr_three_days_before",
                "rapid_test_same_day",
                "pcr_five_days_after"
            ) & 
                symptom_adherence == .8
        ),
    ## With 80% quarantine and 80% symptom screening adherence
    inf_df %>% 
        filter(
            testing_type %in% c(
                "pcr_three_days_before_5_day_quarantine_pcr",
                "rapid_same_day_5_day_quarantine_pcr"
            ) & 
                symptom_adherence == .8 & 
                quarantine_adherence == .8
        )
) 

print_df <- inf_df %>%
    select(testing_cat, metric, mean, p025, p975) %>%
    arrange(testing_cat, metric) %>%
    transmute(testing_cat,
              metric,
              print = case_when(
                  metric %in% c("cume_n_infection_daily", "n_active_infection") ~
                      sprintf("%i (%i, %i)",
                              round(mean),
                              round(p025),
                              round(p975)),
                  TRUE ~ sprintf(
                      "%0.2f (%0.2f, %0.2f)",
                      round(mean, 2),
                      round(p025, 2),
                      round(p975, 2)
                  )
              )) %>%
    pivot_wider(id_cols = testing_cat,
                names_from = metric,
                values_from = print) %>%
    select(
        testing_cat,
        cume_n_infection_daily,
        rel_cume_n_infection_daily
    )

print_df %>%
  kable()
```

## Table S4 
```{r error=FALSE, message=FALSE, warning=FALSE}
## End of travel period infection stats
inf_df <- readRDS(here("data", "summarized_results.RDS")) %>%
    filter(
        time_step == 84, 
        if_threshold == 0,
        prob_inf == PROB_INF,
        risk_multiplier == 2,
        testing_type != "perfect_testing",
        rapid_test_multiplier == .9 |
            is.na(rapid_test_multiplier),
        sens_type != "median" | is.na(sens_type),
        prop_subclin == .3,
        symptom_adherence %in% c(0, .8),
        quarantine_adherence %in% c(0, .8),
        testing_type %in% c(
            "no_testing",
            "pcr_three_days_before",
            "pcr_three_days_before_5_day_quarantine_pcr",
            "rapid_test_same_day",
            "rapid_same_day_5_day_quarantine_pcr",
            "pcr_five_days_after",
            "5_day_quarantine_pcr_five_days_after"
        )
    ) %>%
    shift_time_steps() %>%
    categorize_metric() %>%
    filter(metric %in% c("cume_n_infection_daily",
                         "rel_cume_n_infection_daily"))

## Subset to the main analyses ----
inf_df <- bind_rows(
    ## No testing no symptom screening
    inf_df %>%
        filter(testing_type == "no_testing" &
                   symptom_adherence == 0),
    ## No quarantine 80% symptom screening adherence
    inf_df %>%
        filter(
            testing_type %in% c(
                "pcr_three_days_before",
                "rapid_test_same_day",
                "pcr_five_days_after"
            ) & 
                symptom_adherence == .8
        ),
    ## With 80% quarantine and 80% symptom screening adherence
    inf_df %>% 
        filter(
            testing_type %in% c(
                "pcr_three_days_before_5_day_quarantine_pcr",
                "rapid_same_day_5_day_quarantine_pcr",
                "5_day_quarantine_pcr_five_days_after"
            ) & 
                symptom_adherence == .8 & 
                quarantine_adherence == .8
        )
) 

## Testing statistics 
test_df <- readRDS(here("data", "summarized_testing_results.RDS"))

test_df <- test_df %>%
    filter(
        risk_multiplier == 2,
        testing_type %in% c(
            "no_testing",
            "pcr_three_days_before",
            "pcr_three_days_before_5_day_quarantine_pcr",
            "rapid_test_same_day",
            "rapid_same_day_5_day_quarantine_pcr",
            "pcr_five_days_after",
                "5_day_quarantine_pcr_five_days_after"
        ), 
        metric %in% c("ratio_false_true"),
        rapid_test_multiplier == .9 | is.na(rapid_test_multiplier),
        prob_inf == PROB_INF,
        prop_subclin == .3, 
        sens_type != "median" | is.na(sens_type),
        if_threshold == 0,
        symptom_adherence %in% c(0, .8)
    ) %>%
    categorize_metric()

test_df <- bind_rows(
    ## No testing no symptom screening
    test_df %>%
        filter(testing_type == "no_testing" &
                   symptom_adherence == 0),
    test_df %>%
        filter(testing_type != "no_testing" &
                   symptom_adherence == .8)
) 

## Day of flight statistics
dof_df <- readRDS(here("data", "summarized_results.RDS")) %>%
    filter(
        time_step == 70, 
        if_threshold == 0,
        prob_inf == PROB_INF,
        risk_multiplier == 2,
        testing_type != "perfect_testing",
        rapid_test_multiplier == .9 |
            is.na(rapid_test_multiplier),
        sens_type != "median" | is.na(sens_type),
        prop_subclin == .3,
        symptom_adherence %in% c(0, .8),
        quarantine_adherence %in% c(0, .8),
        testing_type %in% c(
            "no_testing",
            "pcr_three_days_before",
            "pcr_three_days_before_5_day_quarantine_pcr",
            "rapid_test_same_day",
            "rapid_same_day_5_day_quarantine_pcr",
            "pcr_five_days_after",
            "5_day_quarantine_pcr_five_days_after"
        )
    ) %>%
    shift_time_steps() %>%
    categorize_metric() %>%
    filter(metric %in% c("n_active_infection", "rel_n_active_infection"))

dof_df <- bind_rows(
    ## No testing no symptom screening
    dof_df %>%
        filter(testing_type == "no_testing" &
                   symptom_adherence == 0),
    ## No quarantine 80% symptom screening adherence
    dof_df %>%
        filter(
            testing_type %in% c(
                "pcr_three_days_before",
                "rapid_test_same_day",
                "pcr_five_days_after"
            ) & 
                symptom_adherence == .8
        ),
    ## With 80% quarantine and 80% symptom screening adherence
    dof_df %>% 
        filter(
            testing_type %in% c(
                "pcr_three_days_before_5_day_quarantine_pcr",
                "rapid_same_day_5_day_quarantine_pcr",
                "5_day_quarantine_pcr_five_days_after"
            ) & 
                symptom_adherence == .8 & 
                quarantine_adherence == .8
        )
) 

## All main outcomes
all_df <- bind_rows(
    dof_df,
    inf_df,
    test_df
) %>% 
  filter(testing_type == "5_day_quarantine_pcr_five_days_after")

print_df <- all_df %>%
    select(testing_cat, metric, mean, p025, p975) %>%
    arrange(testing_cat, metric) %>%
    transmute(testing_cat,
              metric,
              print = case_when(
                  metric %in% c("cume_n_infection_daily", "n_active_infection") ~
                      sprintf("%i (%i, %i)",
                              round(mean),
                              round(p025),
                              round(p975)),
                  TRUE ~ sprintf(
                      "%0.2f (%0.2f, %0.2f)",
                      round(mean, 2),
                      round(p025, 2),
                      round(p975, 2)
                  )
              )) %>%
    pivot_wider(id_cols = testing_cat,
                names_from = metric,
                values_from = print) %>%
    select(
        testing_cat,
        cume_n_infection_daily,
        rel_cume_n_infection_daily
    )

print_df %>%
  kable()
```
