---
title: "Table 2 (and additional tables)"
author: "Mathew Kiang"
date: "11/15/2020"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setting up
```{r error=FALSE, message=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
library(here)
library(DT)
library(knitr)
source(here("code", "utils.R"))

## Constants ----
PROB_INF <- config::get()$primary_prob_inf / 1000000

results_df <- readRDS(here("data", "summarized_results.RDS"))
testing_df <- readRDS(here("data", "summarized_testing_results.RDS"))

long_table <- bind_rows(
    results_df,
    testing_df,
    results_df %>%
        filter(metric == "rel_n_active_infection", time_step == 70) %>%
        mutate(metric = "rel_n_active_infected_day_of_flight",
               time_step = 84),
    results_df %>%
        filter(metric == "abs_n_active_infection", time_step == 70) %>%
        mutate(metric = "abs_n_active_infected_day_of_flight",
               time_step = 84)
) %>% 
    filter(
      testing_type != "perfect_testing", 
        sens_type == "upper" | is.na(sens_type), 
        time_step == max(time_step),
        if_threshold == 0,
        metric %in% c(
            "cume_w_infection_daily",
            "cume_n_infection_daily",
            "n_active_infected_day_of_flight",
            "ratio_false_true",
            "abs_n_active_infected_day_of_flight",
            "rel_n_active_infected_day_of_flight",
            "abs_cume_n_infection_daily",
            "rel_cume_n_infection_daily",
            "abs_cume_w_infection_daily",
            "rel_cume_w_infection_daily"
        )
    ) %>%
    categorize_metric() %>%
    select(
        testing_type,
        testing_cat,
        prob_inf,
        prob_inf_cat,
        symptom_screening,
        symptom_cat,
        risk_multiplier, 
        risk_multi_cat,
        rapid_test_multiplier, 
        rapid_test_cat,
        metric, 
        metric_cat,
        n:n_total
    ) %>%
    arrange(symptom_cat, testing_cat, metric_cat)

long_table <- bind_rows(
    long_table, 
    long_table %>% 
        filter(testing_type == "no_testing", !symptom_screening) %>%
        mutate(testing_type = "no_testing_no_screening",
               symptom_screening = TRUE)
) %>%
    categorize_testing_types() %>%
    categorize_symptom_screening() %>% 
    filter(testing_type != "no_testing",
           symptom_screening)

table_2_long <- long_table %>%
    filter(
        prob_inf == PROB_INF,
        risk_multiplier == 2,
        rapid_test_multiplier == .9 |
            is.na(rapid_test_multiplier)
    ) %>%
    select(
        testing_type, 
        testing_cat,
        prob_inf_cat, 
        risk_multi_cat,
        rapid_test_cat,
        metric, 
        metric_cat,
        n:n_total
    ) %>%
    arrange(testing_cat, metric_cat)
```

##  Table 2
```{r}
table_2_long %>%
  filter(
    metric %in% c(
      "cume_n_infection_daily",
      "rel_n_active_infected_day_of_flight",
      "ratio_false_true"
    )
  ) %>%
  mutate(
    print_col = case_when(
      grepl("cume_", metric, fixed = TRUE) ~ sprintf(
        "%s (%s, %s)",
        formatC(round(mean, 0), big.mark = ","),
        formatC(round(p025, 0), big.mark = ","),
        formatC(round(p975, 0), big.mark = ",")
      ),
      TRUE ~ sprintf(
        "%0.2f (%0.2f, %0.2f)",
        round(mean, 2),
        round(p025, 2),
        round(p975, 2)
      ),
    ),
    testing_cat_relevel = fct_relevel(
      testing_cat,
      "No testing, no screening",
      "PCR 3 days before",
      "PCR 3 days before + 5-day quarantine + PCR",
      "Same-day RT",
      "Same-day RT + 5-day quarantine + PCR",
      "PCR 3 days after"
    )
  ) %>%
  select(testing_cat_relevel, metric_cat, print_col) %>%
  spread(metric_cat, print_col) %>%
  select(1:2, 4, 3) %>%
  kable()
```

## Extra columns
```{r}
table_2_long %>% 
    mutate(print_col = case_when(
        grepl("cume_", metric, fixed = TRUE) ~ sprintf(
            "%0.1f (%0.1f, %0.1f)",
            round(mean, 1),
            round(p025, 1),
            round(p975, 1)
        ),
        TRUE ~ sprintf(
            "%0.2f (%0.2f, %0.2f)",
            round(mean, 2),
            round(p025, 2),
            round(p975, 2)
        ),
    )) %>%
    select(testing_cat, metric_cat, print_col) %>% 
    DT::datatable(rownames = FALSE, filter = "top")
```
