---
title: "Tables Sx. Sensitivity Analyses"
author: "Mathew Kiang"
date: "1/31/2021"
output: 
  html_document:
    code_folding: 'hide'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(fs)
source(here("code", "utils.R"))
library(DT)
```

## Impact of timing of pre-flight testing on number of active infections on the day of flight

```{r}
## Constants ----
PROB_INF <- config::get()$primary_prob_inf / 1000000

plot_df <- readRDS(here("data", "summarized_testing_results.RDS")) %>%
    filter(
        if_threshold == 0,
        prob_inf == PROB_INF,
        risk_multiplier == 2,
        testing_type != "perfect_testing",
        rapid_test_multiplier == .9 |
            is.na(rapid_test_multiplier),
        prop_subclin == .3, 
        sens_type != "median" | is.na(sens_type),
        symptom_adherence %in% c(.8),
        testing_type %in% c(
          "no_testing",
          "rapid_test_same_day",
          "pcr_three_days_before",
          "pcr_two_days_before",
          "pcr_five_days_before",
          "pcr_seven_days_before"
        )
    ) %>%
    shift_time_steps() %>%
    categorize_metric() %>%
    filter(metric %in% c("n_active_infected_day_of_flight")) %>% 
    categorize_testing_types()

plot_df %>%
    bind_cols(
        plot_df %>% filter(testing_type == "no_testing") %>% select(
            baseline_mean = mean,
            baseline_p025 = p025,
            baseline_p975 = p975
        )
    ) %>%
    transmute(
        testing_cat,
        n_active_infected_day_of_flight =
            sprintf("%d (95%% UI: %d, %d)",
                    round(mean),
                    round(p025),
                    round(p975)),
        rel_reduction = 
            sprintf("%0.2f (95%% UI: %0.2f, %0.2f)",
                    round((mean - baseline_mean) / baseline_mean, 2),
                    round((p025 - baseline_p025) / baseline_p025, 2),
                    round((p975 - baseline_p975) / baseline_p975, 2))
    ) %>%
    arrange(testing_cat) %>%
    datatable(
        rownames = FALSE,
        colnames = c(
            "Testing Strategy",
            "Number of active infections\non day of flight",
            "Relative reduction"
        )
    )
```

## Impact of higher asymptomatic fraction on number of active infections on day of flight
```{r}
plot_df <- readRDS(here("data", "summarized_testing_results.RDS")) %>%
    filter(
        if_threshold == 0,
        prob_inf == PROB_INF,
        risk_multiplier == 2,
        testing_type != "perfect_testing",
        rapid_test_multiplier == .9 |
            is.na(rapid_test_multiplier),
        sens_type != "median" | is.na(sens_type),
        symptom_adherence %in% c(0, .8),
        testing_type %in% c(
            "no_testing",
            "pcr_three_days_before",
            "rapid_test_same_day",
            "pcr_five_days_after"
        )
    ) %>%
    shift_time_steps() %>%
    categorize_metric() %>%
    filter(metric %in% c("n_active_infected_day_of_flight"))

## Subset to the main analyses ----
plot_df <- bind_rows(
    ## No testing no symptom screening
    plot_df %>%
        filter(testing_type == "no_testing" &
                   symptom_adherence == 0),
    ## No quarantine 80% symptom screening adherence
    plot_df %>%
        filter(
            testing_type %in% c(
                "pcr_three_days_before",
                "rapid_test_same_day",
                "pcr_five_days_after"
            ) & 
                symptom_adherence == .8
        )
) 

plot_df %>%
    transmute(
        testing_cat,
        prop_subclin_cat,
        n_active_infected_day_of_flight =
            sprintf("%d (95%% UI: %d, %d)",
                    round(mean),
                    round(p025),
                    round(p975))
    ) %>%
    spread(prop_subclin_cat, n_active_infected_day_of_flight) %>%
    arrange(testing_cat) %>%
    datatable(
        rownames = FALSE,
        colnames = c(
            "Testing Strategy",
            "Number of active infections\non day of flight\nwith 30% asymptomatic infections",
            "Number of active infections\non day of flight\nwith 40% asymptomatic infections"
        )
    )
```

## Impact of test sensitivity on number of active infections on day of flight
```{r}
## Constants ----
PROB_INF <- config::get()$primary_prob_inf / 1000000

plot_df <- readRDS(here("data", "summarized_testing_results.RDS")) %>%
    filter(
        if_threshold == 0,
        prob_inf == PROB_INF,
        risk_multiplier == 2,
        testing_type != "perfect_testing",
        rapid_test_multiplier == .9 |
            is.na(rapid_test_multiplier),
        sens_type != "median" | is.na(sens_type),
        prop_subclin == .3,
        symptom_adherence %in% c(0, .8),
        testing_type %in% c(
            "no_testing",
            "pcr_three_days_before",
            "pcr_three_days_before_5_day_quarantine_pcr",
            "rapid_test_same_day",
            "rapid_same_day_5_day_quarantine_pcr",
            "pcr_five_days_after"
        )
    ) %>%
    shift_time_steps() %>%
    categorize_metric() %>%
    filter(metric %in% c("n_active_infected_day_of_flight"))

## Subset to the main analyses ----
plot_df_upper <- bind_rows(
    ## No testing no symptom screening
    plot_df %>%
        filter(testing_type == "no_testing" &
                   symptom_adherence == 0),
    ## No testing no symptom screening
    plot_df %>%
        filter(testing_type != "no_testing" &
                   symptom_adherence == .8),
) %>% 
    mutate(pcr_sens = "upper")

plot_df <- readRDS(here("data", "summarized_testing_results.RDS")) %>%
    filter(
        if_threshold == 0,
        prob_inf == PROB_INF,
        risk_multiplier == 2,
        testing_type != "perfect_testing",
        rapid_test_multiplier == .9 |
            is.na(rapid_test_multiplier),
        sens_type != "upper" | is.na(sens_type),
        prop_subclin == .3,
        symptom_adherence %in% c(0, .8),
        testing_type %in% c(
            "no_testing",
            "pcr_three_days_before",
            "pcr_three_days_before_5_day_quarantine_pcr",
            "rapid_test_same_day",
            "rapid_same_day_5_day_quarantine_pcr",
            "pcr_five_days_after"
        )
    ) %>%
    shift_time_steps() %>%
    categorize_metric() %>%
    filter(metric %in% c("n_active_infected_day_of_flight"))

## Subset to the main analyses ----
plot_df_median <- bind_rows(
    ## No testing no symptom screening
    plot_df %>%
        filter(testing_type == "no_testing" &
                   symptom_adherence == 0),
    plot_df %>%
        filter(testing_type != "no_testing" &
                   symptom_adherence == .8)
)  %>% 
    mutate(pcr_sens = "median") %>% 
    bind_rows(plot_df_upper)

plot_df_median %>%
    transmute(
        testing_cat,
        pcr_sens,
        n_active_infected_day_of_flight =
            sprintf("%d (95%% UI: %d, %d)",
                    round(mean),
                    round(p025),
                    round(p975))
    ) %>%
    spread(pcr_sens, n_active_infected_day_of_flight) %>%
    arrange(testing_cat) %>%
    datatable(
        rownames = FALSE,
        colnames = c(
            "Testing Strategy",
            "Number of active infections\non day of flight\nwith lower PCR test sensitivity",
            "Number of active infections\non day of flight\nwith baseline PCR test sensitivity"
        )
    )

```

